version: '3'
services:
  web1:
    image: "chinaunicom/counter"
    hostname: "web1"
    ports:
      - "5000:5000"

  web2:
    image: "chinaunicom/counter"
    hostname: "web2"
    ports:
      - "5001:5000"

  web3:
    image: "chinaunicom/counter"
    hostname: "web3"
    ports:
      - "5002:5000"

  redis:
    image: "redis:alpine"

  haproxy:
     build:"./haproxy/"
     depends_on:
       - web1
     volumes:
       - .:/etc/haproxy
     ports:
       - "8000:5555"
